# Numpy

In [3]:
#numpy 
!pip install numpy

In [4]:
import numpy as np

In [5]:
# 1-d array
arr1=np.array([1,2,3,4,5])

In [6]:
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
print(arr1.ndim)

1


In [9]:
#2-d array
arr2=np.array([[1,2,3],[4,5,6]])

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
type(arr2)

numpy.ndarray

In [17]:
print(arr2.ndim)

2


In [18]:
#0-d array
arr=np.array(55)

In [19]:
arr.ndim

0

In [20]:
arr3=np.zeros((2,3))

In [21]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr4=np.ones((2,3))

In [23]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [2]:
import numpy as np

In [3]:
#accessing array elements
arr1=np.array([1,2,3,4,5])
print(arr1[0])

1


In [4]:
arr1[3]

np.int64(4)

In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr1

array([1, 2, 3, 4, 5])

In [1]:
import numpy as np

In [2]:
arr3=np.array([1,2,3,4,5,6,7])
print(arr3[1:5])

[2 3 4 5]


In [3]:
arr4=np.array([1,2,3,4,5,6,7])
print(arr4[4:])


[5 6 7]


In [6]:
arr6=np.array([1,2,3,4,5,6,7])
print(arr6[-3:-1])

[5 6]


In [8]:
#return every other from index 1 to index 5:
arr7=([1,2,3,4,5,6,7])
print(arr7[1:5:2])

[2, 4]


In [5]:
import numpy as np

In [7]:
#shape of an array: shape that return a tuple with each index having then
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [8]:
#Reshape from 1-D to 2-D
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
#iterating arrays
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [11]:
#numpy joining array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [12]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [13]:
#splitting numpy arraays
#splitting is reverse operation of joining.
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [14]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [3]:
#random numbers
#numpy offers the random number module to work with random numbers.
#generate a random integer from to 100:
from numpy import random
x=random.randint(100)
print(x)

81


In [6]:
# random modul's rand() method returns a random flot between 0 and 1.
x=random.rand()
print(x)

0.7617967876432927


In [9]:
#generate random array
x=random.randint(100,size=(10))
print(x)

[85 38 33 60 17 49 54 91 51 88]


In [11]:
#a 2-d array with 3 raws, each raw contaning 5 random integers from 0 to 99
x=random.randint(100,size=(3,5))
print(x)

[[56 31  4 89 50]
 [91 53 56 64 30]
 [87 91  2 42 77]]


In [12]:
#generate a 1-d array contaning 5 random numbers:
x=random.rand(3,5)
print(x)

[[0.45117468 0.35973087 0.24256038 0.21210264 0.52001884]
 [0.21852186 0.77399128 0.60244093 0.2769209  0.73769647]
 [0.50614225 0.212313   0.22582802 0.05290534 0.51249011]]


In [13]:
#generate a 2-d array with 3 raw, each raw  contaning 5 random numbers:
x=random.rand(3,5)
print(x)

[[0.00776294 0.55149309 0.40542957 0.31374488 0.7993639 ]
 [0.77757672 0.10721979 0.79768607 0.1800946  0.4180172 ]
 [0.91708169 0.30198991 0.78153171 0.81512444 0.55255809]]


In [14]:
# searching array
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)


(array([3, 5, 6]),)


In [15]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [17]:
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [18]:
#sort a 2-d array
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [1]:
#Random Distribution
#A random distribution is a set of random numbers that follow a certain probability density function.

from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 5 7 7 3 7 7 7 7 7 7 5 5 7 3 7 5 7 5 7 7 5 5 7 7 7 7 5 7 7 5 7 5 7 7
 3 7 7 7 5 7 7 7 7 7 5 7 5 5 7 5 5 7 7 7 7 5 5 7 7 3 7 5 7 7 7 7 7 7 3 7 7
 3 7 7 5 3 7 7 3 7 7 5 3 7 5 7 7 5 5 5 3 7 5 7 7 5 7]


In [5]:
# let's say we have information of different number of cylinders in a car and we want to display them in a matrix format
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [6]:
print('Sine Function:',np.sin(4))
print('Cosine Function:',np.cos(4))
print('Tan Function',np.tan(4))

Sine Function: -0.7568024953079282
Cosine Function: -0.6536436208636119
Tan Function 1.1578212823495777


In [7]:
np.exp(2)

np.float64(7.38905609893065)

In [8]:
# by default NumPy takes the base of log as e
np.log(2)

np.float64(0.6931471805599453)

In [9]:
## log with base 10
np.log10(8)

np.float64(0.9030899869919435)

In [10]:
#arithmetic on lists

l1 = [1,2,3]
l2 = [4,5,6]
print(l1+l2)

[1, 2, 3, 4, 5, 6]
